### ISSUE TITLE
Just a thanks from us Xbox users 

### ISSUE THREAD

**Issue by danprice142** [basharast/RetrixGold#1]
I hope you don’t mind but I have shared your UWPs to a homebrew community for Xbox One and Series Consoles and many people are very thankful for you work including myself and I would like to invite you to join the community https://discord.gg/Bt9vnKsB68 Thanks for the great work 👍🏻

**Comment by basharast** [comment]
Thanks for your invitation, I just joined, I'm happy to for that since RetriXGold 3 almost done and I need to know if the main interface usable in XBOX
